Repository SathyaBhat/spotify-dl, pull requests merged in 2020-09, with the labels that each got.

#93 Add release drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: chore

#96 save request ids in cache when fetched from Youtube API
  .gitignore
  spotify_dl/cache.py
  spotify_dl/youtube.py
Labels: bug

#97 Fix video id cache
  .gitignore
  spotify_dl/cache.py
  spotify_dl/constants.py
  spotify_dl/models.py
  spotify_dl/spotify.py
  spotify_dl/spotify_dl.py
  spotify_dl/youtube.py
Labels: bug

#98 docs update, bump up version
  CONTRIBUTORS.md
  GETTING_STARTED.md
  README.md
  spotify_dl/constants.py
Labels: major

#84 Add Track Tagging with id3
  spotify_dl/spotify.py
Labels: enhancement, minor
