Repository SathyaBhat/spotify-dl, pull requests merged in 2020-10, with the labels that each got.

#102 bump up Spotipy version
  requirements.txt
  spotify_dl/constants.py
  spotify_dl/spotify.py
  spotify_dl/spotify_dl.py
Labels: chore, major

#103 Update spotify.py
  spotify_dl/spotify.py
Labels: bug, minor

#110 Correct SPOTIPY_REDIRECT_URI to match the env variable
  GETTING_STARTED.md
Labels: minor

#107 Switch to the Playlist API endpoint
  .github/workflows/pythonpackage.yml
  GETTING_STARTED.md
  README.md
  spotify_dl/cache.py
  spotify_dl/constants.py
  spotify_dl/spotify.py
  spotify_dl/spotify_dl.py
  spotify_dl/youtube.py
  tests/test_spotify_fetch_tracks.py
  tests/test_spotify_link.py
Labels: enhancement, major

#114 Sanitize playlist name while saving
  spotify_dl/spotify.py
  spotify_dl/utils.py
  tests/test_spotify_link.py
Labels: bug
