Repository SathyaBhat/spotify-dl, pull requests merged in 2021-04, with the labels that each got.

#166 Dynamically expose file_name function in download_songs
  spotify_dl/spotify.py
  spotify_dl/spotify_dl.py
  spotify_dl/youtube.py
  tests/test_spotify_fetch_tracks.py
Labels: enhancement, minor

#172 Continue to download the playlist if missing files
  .github/workflows/run_tests.yml
  Makefile
  requirements.txt
  spotify_dl/youtube.py
  tests/test_spotify_fetch_tracks.py
Labels: bug, minor

#159 Add dollar sign to clean up list
  spotify_dl/utils.py
Labels: bug, minor

#173 Make album/track/playlist validation as info instead of error
  spotify_dl/constants.py
  spotify_dl/spotify.py
Labels: chore, minor
