Repository SathyaBhat/spotify-dl, pull requests merged in 2022-02, with the labels that each got.

#241 Add Python 3.9 and 3.10 support
  setup.py
Labels: chore

#243 Remove .DS_Store and add it to .gitignore
  .DS_Store
  .gitignore
Labels: chore

#245 Use the tokens found during check
  spotify_dl/scaffold.py
  spotify_dl/spotify_dl.py
Labels: minor, chore

#244 Fix UnboundLocalError
  spotify_dl/spotify_dl.py
Labels: bug, minor

#247 fix download from albums going indefinitely
  spotify_dl/spotify.py
Labels: bug, minor

#248 rename some github actions workflows
  .github/release-drafter.yml
  .github/workflows/prepare-release.yml
  .github/workflows/publish-package.yml
  .github/workflows/tests.yml
Labels: minor, chore

#249 bump up version to 8.1
  spotify_dl/constants.py
Labels: minor, chore
