Repository SathyaBhat/spotify-dl, pull requests merged in 2022-01, with the labels that each got.

#229 Add missed a slash in SAVE_PATH
  spotify_dl/constants.py
Labels: bug, minor

#219 Adding a no-overwrites option that avoids re-downloading a song if it already exists locally
  spotify_dl/spotify_dl.py
  spotify_dl/youtube.py
Labels: enhancement, minor

#232 remove unused files
  spotify_dl/models.py
  spotify_dl/spotify_dl.py
Labels: minor, chore

#233 Fix parsing configuration file
  spotify_dl/spotify_dl.py
Labels: bug, minor

#237 feat: add progress bar using rich progress
  GETTING_STARTED.md
  requirements.txt
  spotify_dl/constants.py
  spotify_dl/scaffold.py
  spotify_dl/spotify.py
  spotify_dl/spotify_dl.py
  spotify_dl/youtube.py
Labels: enhancement, major

#231 Feature to download multiple playlists
  GETTING_STARTED.md
  README.md
  spotify_dl/spotify_dl.py
Labels: enhancement, major

#242 Accept a wider range of versions in requirements
  requirements.txt
Labels: chore
