Repository SathyaBhat/spotify-dl, pull requests merged in 2022-10, with the labels that each got.

#300 added multi processing
  GETTING_STARTED.md
  README.md
  setup.py
  spotify_dl/.gitignore
  spotify_dl/__init__.py
  spotify_dl/constants.py
  spotify_dl/scaffold.py
  spotify_dl/spotify.py
  spotify_dl/spotify_dl.py
  spotify_dl/utils.py
  spotify_dl/youtube.py
  tests/test_spotify_fetch_tracks.py
  tests/test_spotify_link.py
  tests/test_utils.py
  tests/test_youtube.py
Labels: enhancement, minor

#305 Address minor style/nitpicks
  README.md
  images/spotify-playlist.png
  spotify_dl/constants.py
  spotify_dl/scaffold.py
  spotify_dl/spotify.py
  spotify_dl/spotify_dl.py
  spotify_dl/youtube.py
  tests/test_spotify_fetch_tracks.py
Labels: minor, chore

#306 bump up version for release
  spotify_dl/constants.py
Labels: minor, chore

#311 skip sponsorblock by default
  README.md
  requirements.txt
  spotify_dl/spotify_dl.py
  spotify_dl/youtube.py
  tests/test_youtube.py
Labels: bug, minor

#308 Added option to download through a proxy
  spotify_dl/spotify_dl.py
  spotify_dl/youtube.py
Labels: enhancement, minor

#312 release 8.5.0
  GETTING_STARTED.md
  README.md
  spotify_dl/constants.py
Labels: minor, chore
