Repository SathyaBhat/spotify-dl, pull requests merged in 2023-04, with the labels that each got.

#333 Drop query string
  spotify_dl/spotify.py
Labels: bug, minor

#338 v.8.7.0 release
  GETTING_STARTED.md
  spotify_dl/constants.py
  spotify_dl/scaffold.py
  tests/test_spotify_fetch_tracks.py
Labels: minor, chore

#340 Added an option to delete deprecated tracks.
  spotify_dl/spotify.py
  spotify_dl/spotify_dl.py
  spotify_dl/youtube.py
  tests/test_youtube.py
Labels: enhancement, minor
